<a href="https://colab.research.google.com/github/Sinrez/learn_python_course/blob/master/learn_python_data_sci_track.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install openpyxl
# https://data.mos.ru/datasets/752

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openpyxl in /usr/local/lib/python3.9/dist-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.9/dist-packages (from openpyxl) (1.1.0)

In [31]:
import pandas as pd
import numpy as np

In [10]:
import openpyxl

streets = {}

wb_obj = openpyxl.load_workbook('/content/data-398-2023-02-27.xlsx') 
sheet_obj = wb_obj.active 

cell_obj = sheet_obj.cell(row = 1, column = 1) 
print(cell_obj.value)

row = sheet_obj.max_row
column = sheet_obj.max_column
  
print("Total Rows:", row)
print("Total Columns:", column)

cell_obj = sheet_obj['A1': 'B6']
  
# Print value of cell object 
# using the value attribute 
for cell1, cell2 in cell_obj:
    print(cell1.value, cell2.value)

/usr/local/lib/python3.9/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

ID
Total Rows: 11368
Total Columns: 31
ID Name
Локальный идентификатор Наименование
7 «Дербеневская наб.», 3-й Дербеневский переулок (от центра) (7)
11 «Наб. Тараса Шевченко», набережная Тараса Шевченко (в центр) (11)
27 «Кардиоцентр», 3-я Черепковская улица (в центр) (27)
35 «Керамический пр.», Дубнинская улица (в центр) (35)

In [13]:
  # print(cell_obj)
for cell1, cell2  in cell_obj:
        if cell2.value in streets:
            streets[cell2.value] += 1
        else:
            streets[cell2.value] = 1
print(streets)

{'Name': 1, 'Наименование': 1, '«Дербеневская наб.», 3-й Дербеневский переулок (от центра) (7)': 1, '«Наб. Тараса Шевченко», набережная Тараса Шевченко (в центр) (11)': 1, '«Кардиоцентр», 3-я Черепковская улица (в центр) (27)': 1, '«Керамический пр.», Дубнинская улица (в центр) (35)': 1}

In [8]:
import pandas as pd
my_series = pd.Series([4, 7, -5, 3, -1])
my_series

0    4
1    7
2   -5
3    3
4   -1
dtype: int64

In [9]:
my_series[my_series > 0]

0    4
1    7
3    3
dtype: int64

In [16]:
np.exp(my_series)

0      54.598150
1    1096.633158
2       0.006738
3      20.085537
4       0.367879
dtype: float64

In [35]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Маша', 'Вася', 'Эдуард'], 
    'age': [25, 8, 48], 
    'job': ['Программист', 'Школьник', 'Big Boss'],
    'salary': [100, 10, 200]
})
df

     name  age          job  salary
0    Маша   25  Программист     100
1    Вася    8     Школьник      10
2  Эдуард   48     Big Boss     200

In [43]:
df.loc[:0]

   name  age          job  salary
0  Маша   25  Программист     100

In [21]:
df['name']
df[df['age'] > 18]
df.T

                  0         1         2
name           Маша      Вася    Эдуард
age              25         8        48
job     Программист  Школьник  Big Boss
salary          100        10       200

In [42]:
df.iloc[:1]

   name  age          job  salary
0  Маша   25  Программист     100

In [44]:
df.iloc[:1]

   name  age          job  salary
0  Маша   25  Программист     100

In [45]:
import pandas as pd
pd.read_excel(io='/content/data-398-2023-02-27.xlsx', engine='openpyxl')

/usr/local/lib/python3.9/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,ID,Name,Longitude_WGS84,Latitude_WGS84,AdmArea,District,RouteNumbers,StationName,Direction,Pavilion,...,RouteNumbers_en,StationName_en,Direction_en,Pavilion_en,OperatingOrgName_en,EntryState_en,PlaceDescription_en,Works_en,geodata_center,geoarea
0,Локальный идентификатор,Наименование,Долгота в WGS-84,Широта в WGS-84,Административный округ,Район,Маршруты,Название остановки,Направление,Наличие павильона,...,RouteNumbers_en,StationName_en,Direction_en,Pavilion_en,OperatingOrgName_en,EntryState_en,PlaceDescription_en,Works_en,geodata_center,geoarea
1,7,"«Дербеневская наб.», 3-й Дербеневский переулок...",37.6551636,55.72566817,Южный административный округ,Даниловский район,А913; АС932,Дербеневская наб.,от центра,да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.6551636,55.72566817],""type""...",NaN
2,11,"«Наб. Тараса Шевченко», набережная Тараса Шевч...",37.57227413,55.74967848,Западный административный округ,район Дорогомилово,А205; А622,Наб. Тараса Шевченко,в центр,нет,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.57227413,55.74967848],""type...",NaN
3,27,"«Кардиоцентр», 3-я Черепковская улица (в центр...",37.37550932,55.7572642,Западный административный округ,район Кунцево,А660; А798; А816,Кардиоцентр,в центр,да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.37550932,55.7572642],""type""...",NaN
4,35,"«Керамический пр.», Дубнинская улица (в центр)...",37.55724554,55.89460802,Северный административный округ,район Восточное Дегунино,А167; А179; А499; А677; А677к,Керамический пр.,в центр,да,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.55724554,55.89460802],""type...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11362,1009905,"«ЖК «Домашний», Проектируемый проезд № 6276 (в...",37.70341194,55.64720485,Юго-Восточный административный округ,район Марьино,А541; А762; А957; Ат74,ЖК «Домашний»,в центр,нет,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.70341194,55.64720485],""type...",NaN
11363,1009906,"«Курьяновская наб.», Проектируемый проезд № 62...",37.7002543,55.64414191,Юго-Восточный административный округ,район Марьино,А541; А762; А957; Ат74,Курьяновская наб.,в центр,нет,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.7002543,55.64414191],""type""...",NaN
11364,1010496,"«Северный - 9-й мкр.», улица Академика Алихано...",37.53964378,55.92089904,Северо-Восточный административный округ,район Северный,А685; А746; А836; А843; Ан9,Северный - 9-й мкр.,в центр,нет,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.53964378,55.92089904],""type...",NaN
11365,21133,"«МЦД Царицыно», Севанская улица (от центра) (2...",37.6662753,55.61859411,Южный административный округ,район Царицыно,А921; Ам87; Ан13; Ас823; Ас869,МЦД Царицыно,от центра,нет,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.6662753,55.61859411],""type""...",NaN
11366,21235,"«Лефортовский рынок», Авиамоторная улица (от ц...",37.71583694,55.7551631,Юго-Восточный административный округ,район Лефортово,Тм32; Тм46,Лефортовский рынок,от центра,нет,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{""coordinates"":[37.71583694,55.7551631],""type""...",NaN